# code: language=ansible
---
- name: "Install unattended-upgrades package"
  ansible.builtin.apt:
    name: "unattended-upgrades"
    state: "present"

- name: "Template unattended-upgrades configuration"
  ansible.builtin.lineinfile:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades"
    regexp: '^(//)?{{ item.option }}.*'
    line: '{{ item.option }}: "{{ item.value }}";'
  loop: "{{ unattended_upgrade_options }}"
