# code: language=ansible
---
- name: "Disable DNS for SSHD"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(#)?{{ item.option }}.*'
    line: "{{ item.option }} {{ item.value }}"
  loop: "{{ sshd_options }}"
  notify: "Restart sshd"
