name: Execute Tests
on: push
permissions: 
  contents: read

jobs:
  install_dependencies:
    uses: ./.github/workflows/install_dependencies.yml
  
  ansible_lint:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: git_checkout
        uses: actions/checkout@v4

      - name: setup_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: activate_venv
        run: |
          source ./.venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: ansible_lint
        run: |
          ansible-lint
        env:
          FORCE_COLOR: 1

  checkov:
    runs-on: ubuntu-latest
    needs: install_dependencies

    steps:
      - name: git_checkout
        uses: actions/checkout@v4

      - name: setup_cache
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: activate_venv
        run: |
          source ./.venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      # Workaround for missing color output without interactive TTY
      # https://www.checkov.io/4.Integrations/GitLab%20CI.html
      - name: checkov_scan
        run: |
          script -q -c 'checkov ; echo $? > CKVEXIT'
          exit $(cat CKVEXIT)
