name: Install Dependencies
on: workflow_call
permissions: 
  contents: read

jobs:
  python_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: git_checkout
      uses: actions/checkout@v4

    - name: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: setup_poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: '1.8.4'

    - name: setup_cache
      uses: actions/cache@v4
      with:
        path: ./.venv
        key: venv-${{ hashFiles('poetry.lock') }}

    - name: install_packages
      run: poetry install

